### ISSUE TITLE
 Not all project files are in the list

### ISSUE THREAD

**Issue by swwwfactory** [emacs-helm/helm-ls-git#30] opened 2015-06-10 08:29 UTC
After last updates (approx. 8 Jun, possible and 5 Jun) not all files listed in main browse. Only small part are shown.

Forced to use helm-git-grep

**Comment by xuchunyang** [comment] 2015-06-10 08:41
What do you mean by "all project files"? All project files (registered by git) are in "Git files (branch-name)", files ignored by git or under unregistered folder will not be show in "Git status (branch-name)"

**Comment by thierryvolpiatto** [comment] 2015-06-10 09:10
swwwfactory <notifications@github.com> writes:

> After last updates (approx. 8 Jun, possible and 5 Jun) not all files
> listed in main browse. Only small part are shown.

I use this always (for the development of helm) and I can't reproduce,
all files are here, of course as always, the helm-candidate-number-limit
is shown, no more.
IOW if your project is 200 files and helm-candidate-number-limit value
is 100, only 100 files are shown, not the 200, but when you start
narrowing you will see immediately the hidden files if they match.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-06-10 09:17
swwwfactory <notifications@github.com> writes:

> After last updates (approx. 8 Jun, possible and 5 Jun) not all files listed in main browse. Only small part are shown.

Oh! probably you are refering to the buffer list related to project,
which is shown in first source when status is empty (it is recent).
Now helm-ls-git is providing 3 sources:

- status of project (modified files, added etc...)
- buffers in project (the open buffers in this project)
- list of files in project (git ls but limited to candidate-number-limit)

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by swwwfactory** [comment] 2015-06-10 09:25
* all project files is regular files mainly from current working branch

* currently in my project approx. 1282 files

* yes I see now 100 candidates: why not all - git ls very fast

**Comment by thierryvolpiatto** [comment] 2015-06-10 09:50
swwwfactory <notifications@github.com> writes:

>   * yes I see now 100 candidates: why not all - git ls very fast

Nothing have changed about this, I guess you have changed this yourself
in your config.

You can configure this globally (not recommended):

     (setq helm-candidate-number-limit 99999)

Or per source:

     (defmethod helm-setup-user-source ((source helm-ls-git-source))
       (set-slot-value source 'candidate-number-limit 99999))

99999 is just an example.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by swwwfactory** [comment] 2015-06-10 09:56
I set (setq helm-candidate-number-limit 2000) and after restarting I see almost all files in project. 

But when I try filter from browse and file for example with path something like ... Action/Foo/Lib/Common by typing Action Foo Lib Common - it gets empty list :(  

But primordial I see such file. This filtered incorrectly I see.

**Comment by swwwfactory** [comment] 2015-06-10 11:57
I've downgraded version to  Version: 20150607.2332 and its works as expected and nice

**Comment by thierryvolpiatto** [comment] 2015-06-10 14:11
swwwfactory <notifications@github.com> writes:

> I set (setq helm-candidate-number-limit 2000) and after restarting I
> see almost all files in project.

Why almost? You should see all your files if your project have less than
2000 files.


> But when I try filter from browse and file for example with path
> something like ... Action/Foo/Lib/Common by typing Action Foo Lib
> Common - it gets empty list :(

This is another issue and yes I can reproduce this.
It is not related to recent changes, I think it is a long standing bug
we never notice as we are most of the time using basename of files.

I am actually trying to fix it.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-06-10 16:10
Should be fixed now, update also your helm copy.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by swwwfactory** [comment] 2015-06-11 08:22
Now, after update it works as expected and perfectly.

Thanks.

**Comment by thierryvolpiatto** [comment] 2015-06-11 09:56
swwwfactory <notifications@github.com> writes:

> Now, after update it works as expected and perfectly.

Great, thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by swwwfactory** [comment] 2015-06-11 22:16
thanks you too

**Comment by swwwfactory** [comment] 2015-06-13 14:50
After some testing I see another minor issues that after these latest changes helm-resume behaviour is changed too. 

It *seems* that sometime after doing another "resume-aware" operation I see (sometime something like) "filtered state" of helm-ls-git browse. It behaviour can be (sometime) replayed and repeated (but not always). But I expected to see last resume-aware operation as described in helm-resume.

Possible it only seems.

**Comment by thierryvolpiatto** [comment] 2015-06-13 19:20
Can you explain clearly what is a "resume aware" operation ?
And what is "filtered state" ?

**Comment by swwwfactory** [comment] 2015-06-15 08:09
Not all state can be exposed by helm-resume and resume-aware operation its just usual operations that can be activated by helm-resume

filtered state its state after typing some search terms in helm-ls-git 

I try explain incorrect behaviour again

* Go helm-ls-git

* Type for example Foo Bar that can be filtered with some not empty result

* select it by hit enter

* lets try to call helm-resume

* in my case I see empty result

* just try to escape from this by ctrl+g

* now try activate again helm-ls-git

* now performed some incomplete result, seems as filtered state but not very predictable

* if try ctrl+c ctrl+u (refresh) it show filtered state Foo Bar in feature buffer

something like this

**Comment by thierryvolpiatto** [comment] 2015-06-15 10:06
swwwfactory <notifications@github.com> writes:

> Not all state can be exposed by helm-resume and resume-aware operation its just usual operations that can be activated by helm-resume
>
> filtered state its state after typing some search terms in helm-ls-git
>
> I try explain incorrect behaviour again
>
>   * Go helm-ls-git
>    
>   * Type for example Foo Bar that can be filtered with some not empty result
>    
>   * select it by hit enter
>    
>   * lets try to call helm-resume
>    
>   * in my case I see empty result
>    
>   * just try to escape from this by ctrl+g
>    
>   * now try activate again helm-ls-git
>    
>   * now performed some incomplete result, seems as filtered state but not very predictable
>    
>   * if try ctrl+c ctrl+u (refresh) it show filtered state Foo Bar in feature buffer

Thanks for your recipe but I can't reproduce, helm-resume is working as
expected here.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by swwwfactory** [comment] 2015-06-15 14:20
helm-resume working perfectly in my case but not in conjunction with helm-ls-git.

Forced to avoid using helm-resume for helm-ls-git. 

If it occurs - for reset empty list, forced to load something differ than helm-ls-git and enter again to helm-resume so it seems as normal helm-resume state with new

**Comment by thierryvolpiatto** [comment] 2015-06-15 14:40
swwwfactory <notifications@github.com> writes:

> helm-resume working perfectly in my case but not in conjunction with helm-ls-git.

Still can't reproduce, I am able to resume a ls-git session, no
problems.

Are you sure it is not the status source that doesn't show up ?

Here a scenario:

- Run helm-ls-fit from a modified file.
  You have three sources displayed:
  The status source showing modifed file,
  The buffers source showing open buffers for this project.
  The file listing.

- Switch to magit or a terminal or whatever and commit changes to this
  file.

- Run helm-resume
  You have now only two sources displayed, the buffers source and the
  listing of files.

This is normal.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by swwwfactory** [comment] 2015-06-17 23:37
This use-case don't explain broken session of helm-ls-git.  

Lets try explain again.

I see incorrect behaviour in these steps: 
* activate helm-ls-git-ls
* filter something with more than one candidates
* select first and hit enter
* try activate again session

In my case I see these all candidates in during <1 sec and then in next moment all elements cleared from list exclude first element. 

So all another elements cleared from selection list.

Will be great if all elements not cleared from resumed session.

**Comment by thierryvolpiatto** [comment] 2015-06-18 04:09
swwwfactory <notifications@github.com> writes:

> This use-case don't explain broken session of helm-ls-git.
>
> Lets try explain again.
>
> I see incorrect behaviour in these steps:
>
>   * activate helm-ls-git-ls
>   * filter something with more than one candidates
>   * select first and hit enter
>   * try activate again session
>
> In my case I see these all candidates in during <1 sec and then in next moment all elements cleared from list exclude first element.
>
> So all another elements cleared from selection list.
>
> Will be great if all elements not cleared from resumed session.

Yes, of course.
It looks that it was a bug in helm.el I fixed recently (last week I
think), now it is working fine here.
So I wonder, don't you have a old file laying around or have you updated
and recompiled properly helm ?

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by swwwfactory** [comment] 2015-06-18 10:05
I completely remove all related helm and also optional packages, restart emacs, reload, install again these packages: helm helm-git-grep helm-ls-git - nothing change but now selected elements cleared completely.

**Comment by thierryvolpiatto** [comment] 2015-06-18 11:14
swwwfactory <notifications@github.com> writes:

> I completely remove all related helm and also optional packages,
> restart emacs, reload, install again these packages: helm
> helm-git-grep helm-ls-git - nothing change but now selected elements
> cleared completely.

Could you tell me an example of repo where I can reproduce e.g the helm
directory.

1) C-x C-f (helm-find-files) => helm-directory 
2) C-x C-d (helm-browse-project)
3) Enter at prompt "helm fi".
4) Now I have:

Two candidates in "Buffers in project"
Three candidates in "Git files (exp)"

5) Jump to a candidate or C-g
6) M-x helm-resume
   
I have same number of candidates and same candidates in each sources.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by swwwfactory** [comment] 2015-06-18 12:41
This steps produce similar state as explained with "cleared list" or sometime one candidate after helm-resume in my project.
Steps:

I use for example any well know project:
in my case:
cd ~/src
git clone https://github.com/symfony/symfony.git symfony-test

* go to project as you explain
* select file: (I use ~/src/symfony-test/src/Symfony/Component/Debug/Debug.php) 
* Alt+x helm-ls-git
* type something to filter. I type: Context
* browse filtered list of candidates
* select any by hit enter
* see file
* Alt+x helm-resume
* I see filtered list - a few moments (less than one second) seen previously filtered list, and then everything disappears

Also after repeat selection I see strange behaviour with trying open empty buffer but with file name from selection and message in down status: "Use M-x make-directory RET RET to create the directory and its parents"

Bonuses:
* this problem not appears with for example helm project (git clone https://github.com/emacs-helm/helm) 
* this problem also not appears for example another project (git clone https://github.com/zendframework/zend-stdlib)

I think they more simple and have more "flat-structure"

**Comment by thierryvolpiatto** [comment] 2015-06-18 15:56
Ok I could reproduce, not from symfony (can't get it my connection is
too slow, but from emacs repo).

It should not be reproductible if you start by helm-find-files =>
navigate to project => hit C-x C-d => open a file => resume.
Isn't it ?
I will fix it soon.

Thanks for help and sorry for inconvenience.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by thierryvolpiatto** [comment] 2015-06-18 18:01
It should work now, can you try ?

Thanks.

**Comment by swwwfactory** [comment] 2015-06-18 18:20
not working

**Comment by thierryvolpiatto** [comment] 2015-06-18 20:26
swwwfactory <notifications@github.com> writes:

> not working

Yes, I made another commit (by reverting the culprit commit), 
which this time should have fixed it.
It reopen a old bug which is minor compared to this one.
I am actually working on it.

Thanks.

-- 
Thierry
Get my Gnupg key:
gpg --keyserver pgp.mit.edu --recv-keys 59F29997

**Comment by swwwfactory** [comment] 2015-06-18 20:36
Now all works great!

Thanks you too. And also for very useful extensions such as helm-git-grep, helm-occurs and so on :)

**Comment by thierryvolpiatto** [comment] 2015-06-18 21:16
And the old bug is now prevented by not allowing killing helm-current-buffer (not cutting the branch we are sitting on :-)) persistently.
I am closing now.

Thanks.

**Closed by thierryvolpiatto** 2015-06-18 21:16 UTC
